name: badword_guard
description: A Flutter plugin for detecting and filtering out offensive language and bad words in text input.
homepage: https://github.com/xeron56/badword_guard
version: 1.0.1
environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

topics: 
  - badword
  - guard
  - word filter
  - offensive



